/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lazyfarm.server;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.scheduling.annotation.EnableScheduling;

@SpringBootApplication
@RestController
@EnableScheduling
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }

    @GetMapping("/hello")
    public String hello(@RequestParam(value = "name", defaultValue = "World") String name) {
        return String.format("%d. Hello %s!", SheduledTasks.CurrVal, name);
    }

    @GetMapping("/cpu")
    public String getTemperatureCPU() {
        return String.format("CPU %.2f°C", SheduledTasks.TemperatureCPU);
    }


}
